"""Generate the original v0.8.0 Gork notification tones and firmware header."""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import struct
import wave

RATE = 16_000
LEAD_IN_SECONDS = 0.050
PEAK_AMPLITUDE = 30_000
SOUNDS = {
    1: ("ready", [(660, .10), (880, .12)]),
    2: ("confirm", [(880, .15)]),
    3: ("thinking", [(520, .08), (620, .08), (520, .08)]),
    4: ("success", [(660, .09), (880, .09), (1100, .14)]),
    5: ("error", [(330, .13), (220, .18)]),
    6: ("goodbye", [(880, .10), (660, .10), (440, .16)]),
}


def synth(parts):
    # StopWatch powers its codec and speaker amplifier only for playback. A
    # short zero pre-roll lets the rail settle before the first audible edge.
    samples = [0] * round(RATE * LEAD_IN_SECONDS)
    for frequency, seconds in parts:
        count = round(RATE * seconds)
        fade = max(1, round(RATE * .008))
        for index in range(count):
            envelope = min(1.0, index / fade, (count - 1 - index) / fade)
            value = math.sin(2 * math.pi * frequency * index / RATE)
            samples.append(round(value * max(0.0, envelope) * PEAK_AMPLITUDE))
        samples.extend([0] * round(RATE * .018))
    return samples


def write_outputs(root: Path):
    source = root / "01-assets" / "audio" / "source"
    source.mkdir(parents=True, exist_ok=True)
    manifest = {
        "version": 2,
        "sample_rate": RATE,
        "format": "PCM16 mono",
        "peak_amplitude": PEAK_AMPLITUDE,
        "license": "CC0-1.0",
        "sounds": [],
    }
    arrays = []
    total = 0
    for sound_id, (name, parts) in SOUNDS.items():
        samples = synth(parts)
        pcm = struct.pack(f"<{len(samples)}h", *samples)
        wav_path = source / f"{sound_id:02d}-{name}.wav"
        with wave.open(str(wav_path), "wb") as output:
            output.setparams((1, 2, RATE, len(samples), "NONE", "NONE"))
            output.writeframes(pcm)
        total += len(pcm)
        manifest["sounds"].append({
            "id": sound_id, "name": name, "duration_ms": round(len(samples) * 1000 / RATE),
            "sample_rate": RATE, "bytes": len(pcm), "source": "Original deterministic sine synthesis",
            "license": "CC0-1.0", "default_volume": 20,
        })
        words = ",".join(str(value) for value in samples)
        arrays.append(f"static const int16_t kSound{sound_id}[] = {{{words}}};")
    if total > 128_000:
        raise SystemExit(f"PCM budget exceeded: {total}")
    manifest["total_pcm_bytes"] = total
    manifest_path = root / "01-assets" / "audio" / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    header = root / "03-Src" / "stopwatch-grok-avatar" / "src" / "builtin_sounds.h"
    header.parent.mkdir(parents=True, exist_ok=True)
    entries = ",\n".join(
        f'  {{{sound_id}, "{name}", kSound{sound_id}, sizeof(kSound{sound_id}) / sizeof(int16_t)}}'
        for sound_id, (name, _) in SOUNDS.items()
    )
    header.write_text(
        "// Generated by tools/generate_builtin_sounds.py; do not edit.\n#pragma once\n#include <stdint.h>\n#include <stddef.h>\nnamespace gork_sounds {\n"
        + "\n".join(arrays)
        + "\nstruct Sound { uint8_t id; const char* name; const int16_t* pcm; size_t samples; };\n"
        + f"static const Sound kCatalog[] = {{\n{entries}\n}};\n"
        + "static constexpr size_t kCatalogSize = sizeof(kCatalog) / sizeof(kCatalog[0]);\n}\n",
        encoding="utf-8",
    )
    print(f"generated {len(SOUNDS)} sounds, {total} PCM bytes")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    write_outputs(parser.parse_args().root.resolve())
