"""Convert the pinned Bible Strong Grok bot document to firmware tables.

The generated include is data, not a browser engine. No network access or
hardware operation is performed by this script.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "03-Src/stopwatch-grok-avatar/assets/source-grok-bot/avatar-studio-project.json"
OUTPUT = ROOT / "03-Src/stopwatch-grok-avatar/src/grok_bot_catalog.inc"
AVATAR_ID = "avatar-7874f78a-93ec-4536-a3b6-bb53ed744efd"
SOURCE_TO_DESIGN = 1000.0 * 430.0 / (466.0 * 240.0)

# Retain the original input enum order. "sleepy" and the shake-triggered
# "dizzy" are device-facing aliases for the source's drowsy/playful states.
SEQUENCES = (
    "idle", "listening", "thinking", "happy", "excited", "curious",
    "confused", "angry", "surprised", "sad", "drowsy", "playful",
    "sleeping", "waking", "searching", "working", "bored", "suspicious",
    "proud", "shy", "laughing", "scared", "celebrate",
)


def number(value: float) -> str:
    return f"{value:.4f}f"


def pose(expression: dict) -> str:
    spacing = expression["spacing"]
    scale = SOURCE_TO_DESIGN
    eyes = []
    for side, suffix in ((-1, "Left"), (1, "Right")):
        x = (side * spacing / 2 + expression[f"positionX{suffix}"]) * scale
        y = expression[f"positionY{suffix}"] * scale
        width = expression[f"width{suffix}"] * scale
        height = expression[f"height{suffix}"] * scale
        angle = expression["leftAngle" if side < 0 else "rightAngle"]
        eyes.append(
            f"makeAngledEye({number(x)}, {number(y)}, {number(width)}, "
            f"{number(height)}, {number(angle)})"
        )
    # The KK scheduler accepts normalized yaw/pitch and degree roll. This
    # mapping approximates the source 3D orientation while preserving its
    # authored eye dimensions and per-eye offsets.
    return (
        f"makePose({eyes[0]}, {eyes[1]}, 1.0f, 0.0f, 0.0f, "
        f"{number(expression['headY'] / 45.0)}, "
        f"{number(expression['headX'] / 45.0)}, "
        f"{number(expression['headZ'])})"
    )


def render(source: bytes) -> str:
    document = json.loads(source)
    avatars = [a for a in document["library"]["avatars"] if a["id"] == AVATAR_ID]
    expressions = {item["id"]: item for item in document["expressions"]}
    sequences = {item["id"]: item for item in document["sequences"]}
    assert len(avatars) == 1 and avatars[0]["name"] == "Grok bot"
    assert len(expressions) == 27 and len(sequences) == 23
    assert set(SEQUENCES) == set(sequences)
    assert avatars[0]["colors"] == {"body": "#000000", "eyes": "#ffffff"}
    assert avatars[0]["body"]["primary"]["type"] == "sphere"

    lines = [
        "// Generated by tools/generate_grok_bot_catalog.py; do not hand-edit.",
        f"// Source SHA-256: {hashlib.sha256(source).hexdigest()}",
        "// Source: smontlouis/bible-strong-avatar-lab@79fe9ba06e4874b11394b8e8a3f2c493c9d197ba",
        "// Grok bot: 27 presets, 23 sequences. SPDX-License-Identifier: AGPL-3.0-or-later",
        "",
    ]
    for index, name in enumerate(SEQUENCES):
        sequence = sequences[name]
        lines.append(f"const AvatarEngine::Keyframe kBotFrames{index}[] = {{")
        for step in sequence["steps"]:
            expression = expressions[step["expressionId"]]
            transition = {"smooth": "Smooth", "spring": "Spring", "snappy": "Snappy"}.get(step["transition"])
            if transition is None:
                raise ValueError(f"Unsupported transition {step['transition']}")
            lines.append(
                f"    {{{pose(expression)}, {step['transitionMs']}, "
                f"{step['holdMs']}, AvatarEngine::Easing::{transition}}},"
            )
        lines.append("};")
    lines.append("")
    lines.append("const AvatarEngine::ExpressionSpec kExpressions[] = {")
    for index, name in enumerate(SEQUENCES):
        sequence = sequences[name]
        blink = sequence["blink"]
        duration = int(blink["durationMs"])
        mode = {"loop": "Loop", "once": "Once", "pingPong": "PingPong"}.get(sequence["playbackMode"])
        if mode is None:
            raise ValueError(f"Unsupported playback mode {sequence['playbackMode']}")
        blink_values = (
            "true" if blink["enabled"] else "false",
            blink["initialDelayMs"], blink["minIntervalMs"],
            blink["maxIntervalMs"], duration // 2, duration - duration // 2,
        )
        lines.append(
            f'    {{"{name.upper()}", kBotFrames{index}, '
            f'{len(sequence["steps"])}, AvatarEngine::PlaybackMode::{mode}, '
            f'{{{", ".join(map(str, blink_values))}}}, '
            f'kBotNoMotion, {"true" if name == "idle" else "false"}}},'
        )
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render(SOURCE.read_bytes())
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("Grok bot generated catalog is stale")
        print("Grok bot catalog verified: 27 presets, 23 sequences")
    else:
        OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
        print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
